<?php

declare(strict_types=1);

namespace Tests\Unit;

use AhmedSalahDev\CoreAuth\Contracts\PasswordResetManagerInterface;
use AhmedSalahDev\CoreAuth\Services\PasswordResetManager;
use Illuminate\Contracts\Auth\PasswordBroker;
use Illuminate\Contracts\Hashing\Hasher;
use Mockery;
use Mockery\MockInterface;
use PHPUnit\Framework\TestCase;
use RuntimeException;

final class PasswordResetManagerTest extends TestCase
{
    private MockInterface $broker;

    private MockInterface $hasher;

    private PasswordResetManager $passwordResetManager;

    /**
     * Create the Password Broker and Hasher mocks
     * before each test.
     */
    protected function setUp(): void
    {
        parent::setUp();

        $this->broker = Mockery::mock(PasswordBroker::class);
        $this->hasher = Mockery::mock(Hasher::class);

        $this->passwordResetManager = new PasswordResetManager(
            $this->broker,
            $this->hasher
        );
    }

    /**
     * Close all Mockery mocks after each test.
     */
    protected function tearDown(): void
    {
        Mockery::close();

        parent::tearDown();
    }

    /**
     * Verify that PasswordResetManager sends the reset link
     * and returns true when Laravel's Password Broker succeeds.
     */
    public function test_send_reset_link_returns_true_when_successful(): void
    {
        $credentials = [
            'email' => 'user@example.com',
        ];

        $this->broker
            ->shouldReceive('sendResetLink')
            ->once()
            ->with($credentials)
            ->andReturn(PasswordBroker::RESET_LINK_SENT);

        $this->assertTrue(
            $this->passwordResetManager->sendResetLink($credentials)
        );
    }

    /**
     * Verify that sendResetLink returns false when Laravel's Password Broker
     * does not successfully send the reset link.
     */
    public function test_send_reset_link_returns_false_when_unsuccessful(): void
    {
        $credentials = [
            'email' => 'unknown@example.com',
        ];

        $this->broker
            ->shouldReceive('sendResetLink')
            ->once()
            ->with($credentials)
            ->andReturn('passwords.user');

        $this->assertFalse(
            $this->passwordResetManager->sendResetLink($credentials)
        );
    }

    /**
     * Verify that reset successfully changes the user's password
     * using the password hash generated by the configured hasher.
     */
    public function test_reset_returns_true_when_successful(): void
    {
        $credentials = [
            'email' => 'user@example.com',
        ];

        $token = 'valid-reset-token';
        $password = 'new-password';
        $hashedPassword = 'hashed-new-password';

        $user = Mockery::mock();

        $user
            ->shouldReceive('forceFill')
            ->once()
            ->with([
                'password' => $hashedPassword,
            ])
            ->andReturnSelf();

        $user
            ->shouldReceive('save')
            ->once();

        $this->hasher
            ->shouldReceive('make')
            ->once()
            ->with($password)
            ->andReturn($hashedPassword);

        $this->broker
            ->shouldReceive('reset')
            ->once()
            ->withArgs(function (
                array $receivedCredentials,
                callable $callback,
                string $receivedToken
            ) use (
                $credentials,
                $token,
                $user
            ): bool {
                $this->assertSame($credentials, $receivedCredentials);
                $this->assertSame($token, $receivedToken);

                $callback($user);

                return true;
            })
            ->andReturn(PasswordBroker::PASSWORD_RESET);

        $this->assertTrue(
            $this->passwordResetManager->reset(
                $credentials,
                $token,
                $password
            )
        );
    }

    /**
     * Verify that reset returns false when Laravel's Password Broker
     * does not successfully reset the password.
     */
    public function test_reset_returns_false_when_unsuccessful(): void
    {
        $credentials = [
            'email' => 'user@example.com',
        ];

        $token = 'invalid-reset-token';
        $password = 'new-password';

        $this->broker
            ->shouldReceive('reset')
            ->once()
            ->withArgs(function (
                array $receivedCredentials,
                callable $callback,
                string $receivedToken
            ) use (
                $credentials,
                $token
            ): bool {
                $this->assertSame($credentials, $receivedCredentials);
                $this->assertSame($token, $receivedToken);

                return true;
            })
            ->andReturn('passwords.token');

        $this->assertFalse(
            $this->passwordResetManager->reset(
                $credentials,
                $token,
                $password
            )
        );
    }

    /**
     * Verify that exceptions thrown by the Password Broker are propagated
     * to the caller.
     */
    public function test_send_reset_link_propagates_broker_exception(): void
    {
        $credentials = [
            'email' => 'user@example.com',
        ];

        $exception = new RuntimeException(
            'Unexpected password reset failure.'
        );

        $this->broker
            ->shouldReceive('sendResetLink')
            ->once()
            ->with($credentials)
            ->andThrow($exception);

        $this->expectException(RuntimeException::class);
        $this->expectExceptionMessage(
            'Unexpected password reset failure.'
        );

        $this->passwordResetManager->sendResetLink($credentials);
    }

    /**
     * Verify that exceptions thrown by the Password Broker during reset
     * are propagated to the caller.
     */
    public function test_reset_propagates_broker_exception(): void
    {
        $credentials = [
            'email' => 'user@example.com',
        ];

        $token = 'valid-reset-token';
        $password = 'new-password';

        $exception = new RuntimeException(
            'Unexpected password reset failure.'
        );

        $this->broker
            ->shouldReceive('reset')
            ->once()
            ->withArgs(function (
                array $receivedCredentials,
                callable $callback,
                string $receivedToken
            ) use (
                $credentials,
                $token
            ): bool {
                $this->assertSame($credentials, $receivedCredentials);
                $this->assertSame($token, $receivedToken);

                return true;
            })
            ->andThrow($exception);

        $this->expectException(RuntimeException::class);
        $this->expectExceptionMessage(
            'Unexpected password reset failure.'
        );

        $this->passwordResetManager->reset(
            $credentials,
            $token,
            $password
        );
    }

    /**
     * Verify that PasswordResetManager implements the package
     * password reset contract.
     */
    public function test_password_reset_manager_implements_contract(): void
    {
        $this->assertInstanceOf(
            PasswordResetManagerInterface::class,
            $this->passwordResetManager
        );
    }
}